
import java.io.BufferedReader;
import java.io.File;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class GaussEliminationGUI extends javax.swing.JFrame {

    static int i, j, k;
    static double u;

    /**
     * Creates new form GaussEliminationGUI
     */
    public GaussEliminationGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        fileTextField = new javax.swing.JTextField();
        fileButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fileTextArea = new javax.swing.JTextArea();
        solveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("GAUSS ELIMINATION");

        fileTextField.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N

        fileButton.setText("Chọn file");
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });

        fileTextArea.setColumns(20);
        fileTextArea.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fileTextArea.setRows(5);
        jScrollPane2.setViewportView(fileTextArea);

        solveButton.setText("Giải");
        solveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        resultTextArea.setBackground(new java.awt.Color(240, 240, 240));
        resultTextArea.setColumns(20);
        resultTextArea.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        resultTextArea.setRows(5);
        resultTextArea.setBorder(null);
        jScrollPane1.setViewportView(resultTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fileButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))
                                .addGap(18, 18, 18)
                                .addComponent(solveButton)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(false);

        int x = fileChooser.showDialog(this, "Chon file");
        if (x == JFileChooser.APPROVE_OPTION) {
            File f = fileChooser.getSelectedFile();

            fileTextField.setText(f.getAbsolutePath());

            double[][] matrix = loadData(f.getAbsolutePath());

            for (int i = 0; i < matrix.length; i++) {
                StringBuilder line = new StringBuilder();
                for (int j = 0; j < matrix[0].length; j++) {
                    long coef = Math.round(matrix[i][j] * 100000) / 100000;
                    String coefString = coef >= 0 ? "+" + coef : "" + coef;
                    line.append(coefString + ".x" + (j + 1 < matrix.length ? j + 1 : (j + 1 == matrix.length ? j + 1 + "=" : "")) + "");
                }
                line = line.deleteCharAt(0);
                line = line.deleteCharAt(line.length() - 1);
                line = line.deleteCharAt(line.length() - 1);
                if (line.charAt(line.length() - 2) == '+') {
                    line.setCharAt(line.length() - 2, ' ');
                }
                fileTextArea.append(line.toString());
                fileTextArea.append("\n");
            }
        }
    }//GEN-LAST:event_fileButtonActionPerformed

    private void solveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveButtonActionPerformed
        double[] x = solveEquation(loadData(fileTextField.getText()));
        int length = loadData(fileTextField.getText()).length;
        StringBuilder result = new StringBuilder("Kết quả: \n");

        for (int i = 1; i <= length; i++) {
            result.append("x" + i + "=" + (double) Math.round(x[i - 1] * 100000) / 100000 + "\n");
        }

        resultTextArea.setText(result.toString());
    }//GEN-LAST:event_solveButtonActionPerformed

    private static double[][] loadData(String filePath) {
        double[][] matrix = null;
        Path path = Paths.get(filePath);
        Charset charset = Charset.forName("US-ASCII");
        try {
            BufferedReader reader = Files.newBufferedReader(path, charset);
            String firstLine = reader.readLine();
            String[] s = firstLine.split(" ");
            matrix = new double[Integer.parseInt(s[0])][Integer.parseInt(s[1])];
            String nextLine = null;
            int count = 0;
            while ((nextLine = reader.readLine()) != null) {
                String[] elements = nextLine.split(" ");
                for (int i = 0; i < elements.length; i++) {
                    matrix[count][i] = Double.parseDouble(elements[i]);
                }
                count++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return matrix;
    }

    private static double[] solveEquation(double[][] a) {
        int m = a.length;
        int n = a[0].length;

        double[] x = new double[m];
        double sum;
        if (n > m + 1) {
            System.out.println("Phuong trinh co vo so nghiem");
        } else {
            for (k = 0; k < m - 1; k++) {
                for (i = k + 1; i < m; i++) {
                    Thread thread1 = new Thread() {
                        public void run() {
                            u = a[i][k] / a[k][k];
                        }
                    };
                    thread1.run();
                    for (j = k; j < m + 1; j++) {
                        Thread thread2 = new Thread() {
                            public void run() {
                                a[i][j] -= u * a[k][j];
                            }
                        };
                        thread2.run();
                        thread2.stop();
                    }
                    thread1.stop();

                }
            }
            m = m - 1;
            x[m] = a[m][m + 1] / a[m][m];
            for (int i = m - 1; i >= 0; i--) {
                sum = 0;
                for (int j = i + 1; j <= m; j++) {
                    sum += a[i][j] * x[j];
                }
                x[i] = (a[i][m + 1] - sum) / a[i][i];
            }

        }
        return x;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GaussEliminationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GaussEliminationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GaussEliminationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GaussEliminationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GaussEliminationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fileButton;
    private javax.swing.JTextArea fileTextArea;
    private javax.swing.JTextField fileTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea resultTextArea;
    private javax.swing.JButton solveButton;
    // End of variables declaration//GEN-END:variables
}
